---
# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: tomcat-servers
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - selinum: tomcat

- hosts: jenkins
  remote_user: root
  become: yes
 
  roles:
    - deploy
    - build

